# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "papercut"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'


plugins:
  DBIC:
    papercut:
      dsn:  "dbi:SQLite:dbname=papercut.db"
  Auth::RBAC:
    credentials:
      class: DBIC
      options:
        role_name_field: 'rolename'


session: "Simple"
logger: "console"
log: "debug"
show_errors: "1"
access_log: "1"
warnings: "1"
