# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "andrefs.com"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'


plugins:
  DBIC:
    papercut:
      dsn:  "dbi:SQLite:dbname=papercut.db"
      components:
        - 'InflateColumn::Boolean'
  Auth::RBAC:
    credentials:
      class: DBIC
      options:
        role_name_field: 'rolename'
  FlashNote:
    queue: key_multiple
    dequeue: when_used



session: "Simple"
logger: "console"
log: "debug"
show_errors: "1"
access_log: "1"
warnings: "1"


appmenu:
  000_home:
#    text: '<i class="icon-cogs icon-large"></i> Projects'
    text: 'Projects'
    value: http://github.com/andrefs
    #status: disabled
  001_slide:
    text: '<i class="icon-book icon-large"></i> Publications'
    value: http://publications.andrefs.com
  002_grid:
    text: '<i class="icon-globe icon-large"></i> Blog'
    value: /posts
  003_grid:
    text: '<i class="icon-download icon-large"></i> CV'
    value: http://cv.andrefs.com
powered_by:
  text: Dancer
  value: http://dancer.pm/

